### ISSUE TITLE
Julia 0.6 branch

### ISSUE THREAD

**Issue by Cody-G** [JuliaGizmos/GtkReactive.jl#71]
I've prepared a branch with REQUIRE entries pinned to the latest versions that still work with Julia 0.6:

https://github.com/Cody-G/GtkReactive.jl/tree/julia0.6

This has been very useful to ease the transition to 0.7.  If you'd like to add my branch here let me know (and create a `julia0.6` branch for me to submit the PR against).

**Comment by timholy** [comment]
Just checking, is this useful independently of not having master checked out on those branches?

**Comment by timholy** [comment]
Assuming the answer is "yes," I just pushed a `julia0.6` branch.

**Comment by Cody-G** [comment]
Thanks! When using some packages it has been useful.  In the specific case of GtkReactive I don't know, I just pinned things preemptively.  Hopefully it's not needed and the appropriate combination of packages still gets checked out on 0.6 whenever someone does a `Pkg.add("GtkReactive")`
